# Generated by Django 4.0.3 on 2022-04-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetpf', '0002_alter_profile_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('objective', models.CharField(max_length=200)),
                ('income', models.FloatField()),
                ('expense', models.FloatField()),
                ('balance', models.FloatField()),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birth_data', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.DateTimeField()),
                ('occupation', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'personal_info',
            },
        ),
    ]
