# Generated by Django 4.0.3 on 2022-04-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetpf', '0004_alter_addportfolio_expense_alter_addportfolio_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addportfolio',
            name='balance',
        ),
        migrations.AlterField(
            model_name='addportfolio',
            name='date',
            field=models.DateField(),
        ),
    ]
