# Generated by Django 4.0.3 on 2022-04-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetpf', '0005_remove_addportfolio_balance_alter_addportfolio_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addportfolio',
            table='AddPortfolio',
        ),
    ]
